import Head from 'next/head'
import Banner from './components/Banner'
import Chapters from './components/Chapters'
import Footer from './components/Footer'
import FooterBottom from './components/FooterBottom'
import Header from './components/Header'
import Newsletter from './components/Newsletter'
import VerseOfDay from './components/VerseOfDay'
import YellowBg from './components/YellowBg'


export default function Home() {
  return (
    <div className="font-inter">
      <Head>
        <title>Bhagwat Gita</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Banner/>
      <YellowBg/>
      <VerseOfDay/>
      <Newsletter/>

     <Chapters/>
     <Footer/>
     <FooterBottom/>
    </div>
  )
}
